const schools = [
    {
        '_id':'1',
        'name': 'KARAINI HIGH SCHOOL',
        'cutoff':70,
        'image':'/images/school1.jpg',
        'motto':'Discipline begets academic excellence',
        'level': 'sub county',
        'location':'Karaini',
        'status':'mixed day school',
    },
    {
        '_id':'2',
        'name': 'MWEA HIGH SCHOOL',
        'cutoff':50,
        'image':'/images/school2.jpg',
        'motto':'Strive for excellence',
        'level': ' county',
        'location':'Mwea ,kirinyaga county',
        'status':'day and boarding school',
    },
    {
        '_id':'3',
        'name': 'BARICHO HIGH SCHOOL',
        'cutoff':80,
        'image':'/images/school3.jpg',
        'motto':'LEAD THE WAY',
        'level': ' provincial',
        'location':'Kirinyaga, Kerugoya',
        'status':' boarding school',
    },
    {
        '_id':'4',
        'name': 'KIANYAGA HIGH SCHOOL',
        'cutoff':90,
        'image':'/images/school4.jpg',
        'motto':'BETTER YOU BEST',
        'level': 'National',
        'location':'Muranga county',
        'status':' boarding school',
    },
]
export default schools