export const SELECT_ADD_SCHOOL = 'SELECT_ADD_SCHOOL'
export const SELECT_REMOVE_SCHOOL = 'SELECT_REMOVE_SCHOOL'


export const SELECT_SAVE_STUDENTPRIDETAILS = 'SELECT_SAVE_STUDENTPRIDETAILS'
export const SELECT_SAVE_STUDENTPRISCORES = 'SELECT_SAVE_STUDENTPRISCORES'

export const SELECT_CLEAR_ITEMS = 'SELECT_CLEAR_ITEMS'