export const  STUDENT_REGISTER_REQUEST = 'STUDENT_REGISTER_REQUEST'
export const  STUDENT_REGISTER_SUCCESS = 'STUDENT_REGISTER_SUCCESS'
export const  STUDENT_REGISTER_FAIL = ' STUDENT_REGISTER_FAIL'


export const  STUDENT_REGISTERSCORE_REQUEST = 'STUDENT_REGISTERSCORE_REQUEST'
export const  STUDENT_REGISTERSCORE_SUCCESS = 'STUDENT_REGISTERSCORE_SUCCESS'
export const  STUDENT_REGISTERSCORE_FAIL = ' STUDENT_REGISTERSCORE_FAIL'

